version: '3.7'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        depends_on:
          - php-fpm

    php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        volumes:
        - ./:/var/www
        depends_on:
          - mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"

    php-cli:
        build:
            context: ./docker
            dockerfile: php-cli.docker
        volumes:
        - ./:/var/www
        depends_on:
          - mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
        tty: true

    mysql:
        image: mysql:8
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=123"
            - "MYSQL_USER=metrika"
            - "MYSQL_PASSWORD=123"
            - "MYSQL_DATABASE=metrika"
        ports:
        - "33061:3306"


